# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yixiang.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_yixiang(object):
    def setupUi(self, yixiang):
        yixiang.setObjectName("yixiang")
        yixiang.resize(429, 330)
        yixiang.setMinimumSize(QtCore.QSize(410, 300))
        yixiang.setMaximumSize(QtCore.QSize(500, 350))
        font = QtGui.QFont()
        font.setPointSize(9)
        yixiang.setFont(font)
        yixiang.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.body = QtWidgets.QWidget(yixiang)
        self.body.setObjectName("body")
        self.denglu = QtWidgets.QPushButton(self.body)
        self.denglu.setGeometry(QtCore.QRect(110, 260, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.denglu.setFont(font)
        self.denglu.setAutoFillBackground(True)
        self.denglu.setObjectName("denglu")
        self.user_line = QtWidgets.QLineEdit(self.body)
        self.user_line.setGeometry(QtCore.QRect(130, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.user_line.setFont(font)
        self.user_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.user_line.setTabletTracking(False)
        self.user_line.setAutoFillBackground(False)
        self.user_line.setText("")
        self.user_line.setClearButtonEnabled(True)
        self.user_line.setObjectName("user_line")
        self.line = QtWidgets.QFrame(self.body)
        self.line.setGeometry(QtCore.QRect(110, 170, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.body)
        self.line_2.setGeometry(QtCore.QRect(110, 210, 231, 20))
        self.line_2.setToolTipDuration(-1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.key_line = QtWidgets.QLineEdit(self.body)
        self.key_line.setGeometry(QtCore.QRect(130, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.key_line.setFont(font)
        self.key_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.key_line.setTabletTracking(False)
        self.key_line.setClearButtonEnabled(True)
        self.key_line.setObjectName("key_line")
        self.auto_login = QtWidgets.QCheckBox(self.body)
        self.auto_login.setGeometry(QtCore.QRect(110, 230, 71, 16))
        self.auto_login.setObjectName("auto_login")
        self.remember_key = QtWidgets.QCheckBox(self.body)
        self.remember_key.setGeometry(QtCore.QRect(190, 230, 71, 16))
        self.remember_key.setObjectName("remember_key")
        self.zhuce_bt = QtWidgets.QPushButton(self.body)
        self.zhuce_bt.setGeometry(QtCore.QRect(0, 290, 75, 23))
        self.zhuce_bt.setObjectName("zhuce_bt")
        self.find_key = QtWidgets.QPushButton(self.body)
        self.find_key.setGeometry(QtCore.QRect(280, 230, 71, 18))
        self.find_key.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.find_key.setObjectName("find_key")
        self.name = QtWidgets.QLabel(self.body)
        self.name.setGeometry(QtCore.QRect(150, 50, 121, 81))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(self.body)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.body)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 16, 16))
        self.label_3.setObjectName("label_3")
        self.close_win = QtWidgets.QPushButton(self.body)
        self.close_win.setGeometry(QtCore.QRect(400, 0, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.close_win.setFont(font)
        self.close_win.setObjectName("close_win")
        self.min_win = QtWidgets.QPushButton(self.body)
        self.min_win.setGeometry(QtCore.QRect(370, 0, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.min_win.setFont(font)
        self.min_win.setObjectName("min_win")
        self.tishikuang = QtWidgets.QLabel(self.body)
        self.tishikuang.setGeometry(QtCore.QRect(100, 290, 241, 16))
        self.tishikuang.setObjectName("tishikuang")
        yixiang.setCentralWidget(self.body)
        self.toolBar = QtWidgets.QToolBar(yixiang)
        self.toolBar.setObjectName("toolBar")
        yixiang.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(yixiang)
        self.close_win.clicked.connect(yixiang.close)
        self.min_win.clicked.connect(yixiang.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(yixiang)

    def retranslateUi(self, yixiang):
        _translate = QtCore.QCoreApplication.translate
        yixiang.setWindowTitle(_translate("yixiang", "全民医享"))
        self.denglu.setText(_translate("yixiang", "登录"))
        self.auto_login.setText(_translate("yixiang", "自动登录"))
        self.remember_key.setText(_translate("yixiang", "记住密码"))
        self.zhuce_bt.setText(_translate("yixiang", "注册账号"))
        self.find_key.setText(_translate("yixiang", "找回密码"))
        self.name.setText(_translate("yixiang", "11111111111111111111"))
        self.label_2.setText(_translate("yixiang", "TextLabel"))
        self.label_3.setText(_translate("yixiang", "TextLabel"))
        self.close_win.setText(_translate("yixiang", "+"))
        self.min_win.setText(_translate("yixiang", "-"))
        self.tishikuang.setText(_translate("yixiang", "uu"))
        self.toolBar.setWindowTitle(_translate("yixiang", "toolBar"))

