import sys
from PyQt5.QtWidgets import QApplication,QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wuliaobank(object):
    def setupUi(self, wuliaobank):
        wuliaobank.setObjectName("wuliaobank")
        wuliaobank.resize(500, 350)
        wuliaobank.setMinimumSize(QtCore.QSize(500, 350))
        wuliaobank.setMaximumSize(QtCore.QSize(500, 350))
        wuliaobank.setIconSize(QtCore.QSize(30, 30))
        self.body = QtWidgets.QWidget(wuliaobank)
        self.body.setObjectName("body")
        self.log_in = QtWidgets.QPushButton(self.body)
        self.log_in.setGeometry(QtCore.QRect(270, 230, 91, 31))
        self.log_in.setObjectName("log_in")
        self.sign_in = QtWidgets.QPushButton(self.body)
        self.sign_in.setGeometry(QtCore.QRect(140, 230, 81, 31))
        self.sign_in.setObjectName("sign_in")
        self.user_label = QtWidgets.QLabel(self.body)
        self.user_label.setGeometry(QtCore.QRect(80, 90, 61, 21))
        self.user_label.setObjectName("user_label")
        self.key_labal = QtWidgets.QLabel(self.body)
        self.key_labal.setGeometry(QtCore.QRect(80, 150, 51, 21))
        self.key_labal.setObjectName("key_labal")
        self.key_remember = QtWidgets.QCheckBox(self.body)
        self.key_remember.setGeometry(QtCore.QRect(160, 200, 71, 16))
        self.key_remember.setObjectName("key_remember")
        self.auto_go = QtWidgets.QCheckBox(self.body)
        self.auto_go.setGeometry(QtCore.QRect(260, 200, 71, 16))
        self.auto_go.setObjectName("auto_go")
        self.user_line = QtWidgets.QLineEdit(self.body)
        self.user_line.setEnabled(True)
        self.user_line.setGeometry(QtCore.QRect(140, 90, 211, 31))
        self.user_line.setText("")
        self.user_line.setObjectName("user_line")
        self.key_line = QtWidgets.QLineEdit(self.body)
        self.key_line.setGeometry(QtCore.QRect(140, 150, 211, 31))
        self.key_line.setMouseTracking(True)
        self.key_line.setAutoFillBackground(False)
        self.key_line.setText("")
        self.key_line.setObjectName("key_line")
        wuliaobank.setCentralWidget(self.body)
        self.head = QtWidgets.QMenuBar(wuliaobank)
        self.head.setGeometry(QtCore.QRect(0, 0, 500, 23))
        self.head.setObjectName("head")
        self.vip = QtWidgets.QMenu(self.head)
        self.vip.setObjectName("vip")
        self.nocard = QtWidgets.QMenu(self.head)
        self.nocard.setObjectName("nocard")
        self.helppeople = QtWidgets.QMenu(self.head)
        self.helppeople.setObjectName("helppeople")
        self.menu = QtWidgets.QMenu(self.head)
        self.menu.setObjectName("menu")
        wuliaobank.setMenuBar(self.head)
        self.last = QtWidgets.QStatusBar(wuliaobank)
        self.last.setSizeGripEnabled(True)
        self.last.setObjectName("last")
        wuliaobank.setStatusBar(self.last)
        self.actionwuliaoyinhang = QtWidgets.QAction(wuliaobank)
        self.actionwuliaoyinhang.setObjectName("actionwuliaoyinhang")
        self.actionzhuce = QtWidgets.QAction(wuliaobank)
        self.actionzhuce.setObjectName("actionzhuce")
        self.join = QtWidgets.QAction(wuliaobank)
        self.join.setObjectName("join")
        self.zhuanzhang = QtWidgets.QAction(wuliaobank)
        self.zhuanzhang.setObjectName("zhuanzhang")
        self.lilv = QtWidgets.QAction(wuliaobank)
        self.lilv.setObjectName("lilv")
        self.action_8 = QtWidgets.QAction(wuliaobank)
        self.action_8.setObjectName("action_8")
        self.action_10 = QtWidgets.QAction(wuliaobank)
        self.action_10.setObjectName("action_10")
        self.fileOpenAction = QtWidgets.QAction(wuliaobank)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileNewAction = QtWidgets.QAction(wuliaobank)
        self.fileNewAction.setObjectName("fileNewAction")
        self.fileCloseAction = QtWidgets.QAction(wuliaobank)
        self.fileCloseAction.setObjectName("fileCloseAction")
        self.vip.addSeparator()
        self.vip.addAction(self.join)
        self.vip.addSeparator()
        self.vip.addAction(self.action_8)
        self.vip.addSeparator()
        self.nocard.addSeparator()
        self.nocard.addAction(self.zhuanzhang)
        self.nocard.addSeparator()
        self.nocard.addAction(self.action_10)
        self.helppeople.addSeparator()
        self.helppeople.addAction(self.lilv)
        self.helppeople.addSeparator()
        self.menu.addAction(self.fileOpenAction)
        self.menu.addAction(self.fileNewAction)
        self.menu.addAction(self.fileCloseAction)
        self.head.addAction(self.vip.menuAction())
        self.head.addAction(self.nocard.menuAction())
        self.head.addAction(self.helppeople.menuAction())
        self.head.addAction(self.menu.menuAction())
        self.user_line.setPlaceholderText('Please enter your username')  # 添加提示字符
        self.key_line.setPlaceholderText('Please enter your password')

        self.retranslateUi(wuliaobank)
        QtCore.QMetaObject.connectSlotsByName(wuliaobank)
        wuliaobank.setTabOrder(self.log_in, self.sign_in)
        wuliaobank.setTabOrder(self.sign_in, self.key_remember)
        wuliaobank.setTabOrder(self.key_remember, self.auto_go)

    def retranslateUi(self, wuliaobank):
        _translate = QtCore.QCoreApplication.translate
        wuliaobank.setWindowTitle(_translate("wuliaobank", "无聊bank"))
        self.log_in.setText(_translate("wuliaobank", "登录"))
        self.sign_in.setText(_translate("wuliaobank", "注册"))
        self.user_label.setText(_translate("wuliaobank", "用户名："))
        self.key_labal.setText(_translate("wuliaobank", "密码："))
        self.key_remember.setText(_translate("wuliaobank", "记住密码"))
        self.auto_go.setText(_translate("wuliaobank", "自动登录"))
        self.vip.setTitle(_translate("wuliaobank", "会员服务"))
        self.nocard.setTitle(_translate("wuliaobank", "无卡服务"))
        self.helppeople.setTitle(_translate("wuliaobank", "便民服务"))
        self.menu.setTitle(_translate("wuliaobank", "文件"))
        self.actionwuliaoyinhang.setText(_translate("wuliaobank", "denglu"))
        self.actionzhuce.setText(_translate("wuliaobank", "zhuce"))
        self.join.setText(_translate("wuliaobank", "加入我们"))
        self.zhuanzhang.setText(_translate("wuliaobank", "无卡转账"))
        self.lilv.setText(_translate("wuliaobank", "利率查看"))
        self.action_8.setText(_translate("wuliaobank", "更多信息"))
        self.action_10.setText(_translate("wuliaobank", "无卡查询"))
        self.fileOpenAction.setText(_translate("wuliaobank", "打开"))
        self.fileNewAction.setText(_translate("wuliaobank", "新建"))
        self.fileCloseAction.setText(_translate("wuliaobank", "关闭"))



class MyWindow(QMainWindow, Ui_wuliaobank):
    def __init__(self,parent=None):
        super(MyWindow,self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    myWin = MyWindow()
    myWin.show()
    sys.exit(app.exec_())